pipeline {
    agent any
    environment {
        MYSQL_ROOT_PASSWORD=credentials("MYSQL_ROOT_PASSWORD")
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                docker build -t jasonatkins/task2-db Task2/db
                docker build -t jasonatkins/task2-app Task2/flask-app
                '''
            }

        }
        stage('Push') {
            steps {
                sh '''
                docker push jasonatkins/task2-db
                docker push jasonatkins/task2-app
                '''
            }

        }
        stage('Deploy') {
            steps {
                sh '''
                    sed -e 's,{{password}},'${MYSQL_ROOT_PASSWORD}',g;' db-password.yaml | kubectl apply -f -
                    kubectl apply -f Task2/task2-db-manifest.yaml
                    kubectl apply -f Task2/nginx-configMap.yaml
                    kubectl apply -f Task2/task2-app-manifest.yaml
                    kubectl apply -f Task2/nginx-manifest.yaml
                '''
            }

        }

    }

}

