pipeline {
    agent any
    environment {
        YOUR_NAME=credentials("YOUR_NAME")
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                docker build -t jasonatkins/task2-db Task2/db
                docker build -t jasonatkins/task2-app Task2/flask-app
                '''
            }

        }
        stage('Push') {
            steps {
                sh '''
                docker push jasonatkins/task2-db
                docker push jasonatkins/task2-app
                '''
            }

        }
        stage('Deploy') {
            steps {
                sh '''
                    kubectl apply -f Task2
                '''
            }

        }

    }

}

