apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec: 
  containers:
  - name: mysql
    image: jasonatkins/task2-db:latest
    env: 
    - name: MYSQL_ROOT_PASSWORD
      value: password

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector: 
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
